import type { Content } from './types'

export const en: Content = {
  locale: 'en',
  nativeName: 'English',
  shortName: 'EN',
  htmlLang: 'en',
  documentTitle: 'Siccus — hortus siccus',

  ui: {
    kicker: 'Siccus · hortus siccus',
    placeholder: 'a word',
    defaultWord: 'Éléa',
    exportSvg: 'SVG',
    exportPng: 'PNG',
    variants: {
      mounted: 'Mounted sheet',
      bare: 'Bare sheet',
      grid: 'Gridded paper',
    },
    caption: '{port} — {palette} palette',
    languageLabel: 'Language',
  },

  plate: {
    header: 'HERBARIUM SICCUS',
    headerRight: 'HORTUS SICCUS DIGITALIS · PL. A3',
    tagline: 'A deterministic collection — one word, one specimen',
    folioLine: 'f. {folio} · no. {specimen}',
    spine: 'SICCUS · SPECIMEN NO. {specimen} · {palette}',
    detail1: '1. SINGLE LEAF, LOWER SURFACE — ×{scale}',
    detail1Sheathing: '1. SINGLE BLADE, SHEATHING BASE — ×{scale}',
    detail2: '2. {kind} — ×{scale}',
    detailKinds: {
      coupe: 'STEM CROSS-SECTION',
      graine: 'RIPE SEED',
      ombelle: 'INFLORESCENCE',
    },
    scaleLabel: 'SCALE OF SUBJECT',
    scaleZero: '0',
    scaleMax: '{cm} cm',
    notaLabel: 'NOTA',
    diagnosis: '{port} · {phyllotaxy} phyllotaxy · {margin} margin',
    fields: {
      familia: 'FAMILIA',
      locus: 'LOCUS',
      altitudo: 'ALTITUDO',
      determinavit: 'DETERMINAVIT',
      dies: 'DIES',
      legit: 'LEGIT',
      herbNo: 'HERB. NO.',
    },
    footer:
      'Plate generated by Siccus — the word is the only input; the same word yields the same specimen. Keep out of direct light.',
  },

  handwriting: {
    altitude: '{altitude} m, southern aspect',
    collector: 'S. Boulery',
    herbNo: '{specimen} bis',
    revision: '→ {latin}',
    revisedOn: 'rev. {date}',
    marginNote: 'sheet to be remounted',
  },

  stamp: {
    title: 'HERB. SICCUS',
    subtitle: 'ACCESSIONED',
  },

  palettes: {
    sepia: 'sepia',
    olive: 'dried olive',
    encre: 'cold ink',
    tabac: 'tobacco',
    fusain: 'charcoal',
  },

  ports: {
    arbustif: 'shrubby habit, branched',
    rosette: 'rosette habit, flowering scape',
    graminee: 'grass-like habit, tufted',
    grimpant: 'climbing habit, tendrils',
    fougere: 'habit of pinnate fronds',
  },

  phyllotaxies: {
    alterne: 'alternate',
    opposee: 'opposite',
    verticillee: 'whorled',
  },

  margins: {
    entiere: 'entire',
    dentee: 'toothed',
    lobee: 'lobed',
  },

  /* Collection sites — herbarium Latin, deliberately identical across locales.
     Exactly 7: the seed draws an index into this list. */
  loci: [
    'in rupibus calcareis, Vallis Umbrosa',
    'ad ripas fluminis Aquae Nigrae',
    'in pascuis siccis supra Montem Cinereum',
    'in fissuris muri antiqui, Hortus Vetus',
    'ad margines silvae, Saltus Boreus',
    'in arenosis maritimis, Litus Album',
    'in dumetis umbrosis prope Fontem Frigidam',
  ],

  /* Collector's notes. Exactly 8: the seed draws two indices into this list. */
  notes: [
    'stipules caducous, barely visible',
    'resinous scent when bruised',
    'venation prominent beneath',
    'taproot, intensely bitter',
    'flowers not observed on this individual',
    'exsiccatum slightly discoloured',
    'blade somewhat fleshy, brittle when dry',
    'decumbent at the base, then erect',
  ],
}
